version: '3'

services:
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /tmp/demo-realm.json
    volumes:
      - ./demo-realm.json:/tmp/demo-realm.json
    ports:
      - 18080:8080
      - 18443:8443
